### ISSUE TITLE
The slime boss on the pacifist challenge is unbeatable

### ISSUE THREAD

**Issue by dragon-master6** [ruiner189/CustomChallenges#4]
![20220906180749_1](https://user-images.githubusercontent.com/112942537/188610593-6c6beaf1-96c1-4187-bd0d-89c8bc5f3397.jpg)

**Comment by ruiner189** [comment]
Thanks for the bug report! The next version should have this fixed.
![image](https://user-images.githubusercontent.com/47389474/189219366-a92c31db-39ea-4928-b933-b7a671fa48b8.png)
